# Generated by Django 6.0.1 on 2026-02-27 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('fermee', 'Fermée')], default='ouverte', max_length=10)),
                ('carburant_disponible', models.BooleanField(default=True)),
                ('nombre_vehicules', models.PositiveIntegerField(default=0)),
                ('niveau_affluence', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('forte', 'Forte')], default='faible', max_length=10)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueCapteurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vehicules', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='stations.stationservice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
