# Generated by Django 6.0.1 on 2026-02-27 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stationservice',
            name='gestionnaire',
            field=models.ForeignKey(blank=True, help_text='Utilisateur responsable de la mise à jour de cette station.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations_geres', to=settings.AUTH_USER_MODEL),
        ),
    ]
